name: Bonfire8458/flarum-export-posts PHP

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@main
    with:
      enable_backend_testing: true

      backend_directory: .
